###############################################################################
# Filename: Assignment 2: Hydropower Consumption
# Author: Rachel Lindgren
# Date: 25 Apr 2022
# Description: This program will tell the user how much energy was generated
#              by hydropower and other sources
# Input: Energy consumption csv file
# Output: Power generation by year for any or all included energy sources
###############################################################################

# import data and packages
import pandas as pd
import numpy as np
worldpower = pd.read_csv("C:/Users/rache/Documents/ENGR103/"
                         "energy_use_terrawatthours.csv")
print(worldpower)

#Generate list of energy sources and set up data for manipulation
years = worldpower.iloc[:,1] #shows year column
power_source = worldpower.iloc[:,2] #shows energy source (variable) column
energy_gen = worldpower.iloc[:,3] #shows generation_twh column
renewables = ["Bioenergy", "Hydro", "Nuclear", "Other Renewables",
              "Solar", "Wind"] #creates list of renewables
nonrenewables = ["Coal", "Gas", "Other Fossil"] #creates list of fossil fuels
selectable_sources = renewables + nonrenewables #combines the lists

#Calculating power from all sources in the selected year
cntr1 = 0
cntr2 = 0
clean_power = np.empty(22)
fossil_power = np.empty(22)
year_store = np.empty(22)
for x in range(len(years)): # stores clean and fossil energy generated by year
    if power_source[x] == "Clean": # stores clean energy
        clean_power[cntr1] = energy_gen[x]
        year_store[cntr1] = years[x]
        cntr1 = cntr1 + 1
    if power_source[x] == "Fossil": # stores fossil energy
        fossil_power[cntr2] = energy_gen[x]
        cntr2 = cntr2 + 1

for x in range(len(clean_power)): # will print total world energy gen by year
    if year_store[x] == 2000:
        print("The total energy produced in", int(year_store[x]), "was",
              np.floor(clean_power[x] + fossil_power[x]), "twh.")
        power_2000 = np.floor(clean_power[x] + fossil_power[x])
    if year_store[x] == 2021:
        print("The total energy produced in", int(year_store[x]), "was",
              np.floor(clean_power[x] + fossil_power[x]), "twh.")
        power_2021 = np.floor(clean_power[x] + fossil_power[x])

power_change = power_2021 - power_2000
power_change_percent = power_change / power_2000 * 100
print("World power generation has increased by", np.floor(power_change_percent)
      , "% over the past 20 years.")

#Calculating hydropower in two years
cntr3 = 0
hydro_power = np.empty(22)
year_store = np.empty(22)
for x in range(len(years)): # stores hydro energy generated each year
    if power_source[x] == "Hydro": # stores hydro energy
        hydro_power[cntr3] = energy_gen[x]
        year_store[cntr3] = years[x]
        cntr3 = cntr3 + 1

for x in range(len(hydro_power)): # will print total world energy generation
                                  # from hydro each year
    if year_store[x] == 2000:
        print("The total energy produced from hydropower in",
              int(year_store[x]), "was", np.floor(hydro_power[x]), "twh.")
        hp_2000 = np.floor(hydro_power[x])
    if year_store[x] == 2021:
        print("The total energy produced from hydropower in",
              int(year_store[x]), "was", np.floor(hydro_power[x]), "twh.")
        hp_2021 = np.floor(hydro_power[x])

print("This is a difference of ", (hp_2021 - hp_2000), "twh.")

#Percent of world power coming from hydro
hp_world_frac_2000 = hp_2000 / power_2000 * 100
hp_world_frac_2021 = hp_2021 / power_2021 * 100

print("In 2000", round(hp_world_frac_2000, 1),
      "% of world energy came from hydropower, "
    "and in 2021", round(hp_world_frac_2021, 1),
      "% of world energy came from hydropower.")


#Get user inputs for other energy sources
power_source_1 = input("Please choose an energy source from this list except "
                       "for Hydro: " + str(selectable_sources) + ":")
power_source_2 = input("Please choose another energy source from this list "
                       "except for Hydro and first source you chose: " +
                       str(selectable_sources) + ":")

#Calculating energy generation from other sources
cntr4 = 0
cntr5 = 0
other_power1 = np.empty(22)
other_power2 = np.empty(22)
year_store = np.empty(22)
for x in range(len(years)): # stores first other energy generated each year
    if power_source[x] == power_source_1:
        year_store[cntr4] = years[x]
        other_power1[cntr4] = energy_gen[x]
        cntr4 = cntr4 + 1
    if power_source[x] == power_source_2:  # stores second other energy
        year_store[cntr5] = years[x]
        other_power2[cntr5] = energy_gen[x]
        cntr5 = cntr5 + 1

for x in range(len(other_power1)):  # will print total world energy generation
                                    # from other sources in 2000
    if year_store[x] == 2000:
        print("The total energy produced from", (power_source_1),
              "in", int(year_store[x]), "was", (other_power1[x]),
              "twh. The total energy produced from", (power_source_2), "in",
              int(year_store[x]), "was", (other_power2[x]), "twh.")
        other1_2000 = other_power1[x]
        other2_2000 = other_power2[x]

for x in range(len(other_power1)):  # will print total world energy generation
                                    # from other sources in 2021
    if year_store[x] == 2021:
        print("The total energy produced from", (power_source_1),
              "in", int(year_store[x]), "was", (other_power1[x]),
              "twh. The total energy produced from", (power_source_2), "in",
              int(year_store[x]), "was", (other_power2[x]), "twh.")
        other1_2021 = other_power1[x]
        other2_2021 = other_power2[x]

other1_world_frac_2000 = other1_2000 / power_2000 * 100
other2_world_frac_2000 = other2_2000 / power_2000 * 100
other1_world_frac_2021 = other1_2021 / power_2021 * 100
other2_world_frac_2021 = other2_2021 / power_2021 * 100

print("In 2000,", round(other1_world_frac_2000, 1),
      "% of world energy came from", power_source_1, "and in 2021,",
      round(other1_world_frac_2021, 1), "% of world energy came from",
      power_source_1, ".")
print("In 2000,", round(other2_world_frac_2000, 1), "% of world "
      "energy came from", power_source_2, "and in 2021,",
      round(other2_world_frac_2021, 1), "% of world energy came from",
      power_source_2, ".")


#This is my garbage code that doesn't work and I don't know why

#clean_power = np.empty(22)
#fossil_power = np.empty(22)
#year_store = np. empty(22)

#for x in range(len(years)): # stores clean and fossil energy generated each year
#     if years[x] == selected_year:
#         if power_source[x] == "Clean": # stores clean energy
#             clean_power = energy_gen[x]
#     #if years[x] == selected_year:
#         if power_source[x] == "Fossil": # stores fossil energy
#             fossil_power = energy_gen[x]
#     break
#
# tot_power = clean_power + fossil_power
# print("total power:", tot_power)
#
# for x in range(len(clean_power)): # will print total world energy generation for the selected year
#     if years[x] == selected_year and (clean_power[x] != 0 or fossil_power[x] != 0):
#         print("The total energy produced in", selected_year, "was", fossil_power[x] + clean_power[x], "twh.")